-- 기존 DB에 T_ASK가 짧은 스키마만 있을 때 1회 실행 (Unknown column 'A_TEL' 등 오류 시)
-- 이미 컬럼이 있으면 해당 줄은 에러 → 건너뛰거나 주석 처리

ALTER TABLE `T_ASK`
  ADD COLUMN `A_TEL` varchar(500) DEFAULT NULL AFTER `A_NAME`,
  ADD COLUMN `A_MAIL` varchar(500) DEFAULT NULL AFTER `A_TEL`,
  ADD COLUMN `A_URL` varchar(500) DEFAULT NULL AFTER `A_MAIL`,
  ADD COLUMN `A_ID` varchar(100) DEFAULT NULL AFTER `A_URL`,
  ADD COLUMN `A_TYPE` varchar(500) DEFAULT NULL AFTER `A_ID`,
  ADD COLUMN `A_TYPE_GUBUN1` varchar(200) DEFAULT NULL AFTER `A_TYPE`,
  ADD COLUMN `A_TYPE_GUBUN2` varchar(500) DEFAULT NULL AFTER `A_TYPE_GUBUN1`,
  ADD COLUMN `A_TYPE_GUBUN3` varchar(500) DEFAULT NULL AFTER `A_TYPE_GUBUN2`,
  ADD COLUMN `A_CORP_NAME` varchar(500) DEFAULT NULL AFTER `A_RE_YN`,
  ADD COLUMN `A_JIK` varchar(200) DEFAULT NULL AFTER `A_CORP_NAME`,
  ADD COLUMN `A_PROJECT_DT` varchar(200) DEFAULT NULL AFTER `A_JIK`,
  ADD COLUMN `A_CONNET` varchar(255) DEFAULT NULL AFTER `A_PROJECT_DT`,
  ADD COLUMN `A_MARKET_YN` char(1) DEFAULT 'N' AFTER `A_CONNET`,
  ADD COLUMN `A_MARKET2_YN` char(1) DEFAULT 'N' AFTER `A_MARKET_YN`,
  ADD COLUMN `A_FILE1` varchar(500) DEFAULT NULL AFTER `A_MARKET2_YN`,
  ADD COLUMN `A_SYSFILE1` varchar(500) DEFAULT NULL AFTER `A_FILE1`,
  ADD COLUMN `A_ETC_MEMO` mediumtext AFTER `A_SYSFILE1`;
